services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ffaas
      POSTGRES_USER: ffaas
      POSTGRES_PASSWORD: ffaas
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ffaas" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"
