name: CI

on:
  push:
    branches: [ ci, develop ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Restore
        run: dotnet restore FfaasLite.sln

      - name: Build (Release, no-restore)
        run: dotnet build FfaasLite.sln -c Release --no-restore /warnaserror

      - name: Test (with trx + coverage)
        run: dotnet test tests/FfaasLite.Tests/FfaasLite.Tests.csproj -c Release --no-build --logger "trx;LogFileName=test_results.trx" /p:CollectCoverage=true /p:CoverletOutput=./TestResults/coverage/ /p:CoverletOutputFormat="lcov%2copencover"

      - name: Upload test results (trx)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          path: |
            **/TestResults/**/*.trx
            **/TestResults/**/coverage.*

  dockerfile-lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile